version: '3.9'

services:
  mapping-mediator-config-importer:
    image: jembi/instantohie-config-importer
    deploy:
      restart_policy:
        condition: none
    configs:
      - source: mediator-config-metadata.js
        target: /metadata.js
      - source: mediator-config-jsonToFhirLabOrder.json
        target: /jsonToFhirLabOrder.json
    networks:
      mapping-mediator:
    # This command will only attempt to import the config when the uptime responds with a 2xx
    command: sh -c "wait-on -t 60000 http-get://openhim-mapping-mediator:3003/uptime && node /metadata.js"
    # command: sh -c "wait-on -t 60000 http-get://openhim-mapping-mediator_openhim-mapping-mediator:3003/uptime && node /metadata.js"

configs:
  mediator-config-metadata.js:
    file: ./metadata.js
    name: mediator-config-metadata.js-${mediator_config_metadata_js_DIGEST:?err}
    labels:
      name: jempi
  mediator-config-jsonToFhirLabOrder.json:
      file: ./jsonToFhirLabOrder.json
      name: mediator-config-jsonToFhirLabOrder.json-${mediator_config_jsonToFhirLabOrder_json_DIGEST:?err}
      labels:
        name: fhir

networks:
  mapping-mediator:
    name: openhim_mapping_mediator_public
    external: true
